sequenceDiagram
    participant صاحب تراکنش
    participant سرویس پرداخت
    participant درگاه پرداخت
    participant وب‌هوک

    صاحب تراکنش->>سرویس پرداخت: POST /payment/transaction
    alt settelment == true
        سرویس پرداخت->>درگاه پرداخت: هدایت
    else settlement == null || false
        سرویس پرداخت-->>صاحب تراکنش: تراکنش با موفقیت ایجاد شد
        صاحب تراکنش->>سرویس پرداخت: POST /payment/transaction/{id}/settlement
        سرویس پرداخت->>درگاه پرداخت: هدایت
    end

    par
        loop هر ۵ دقیقه
            سرویس پرداخت->>درگاه پرداخت: بررسی وضعیت پرداخت
            alt پرداخت انجام شده است
                درگاه پرداخت-->>سرویس پرداخت: پرداخت تکمیل شد
            else
                سرویس پرداخت->>سرویس پرداخت: منتظر تلاش بعدی استعلام
            end
        end
        درگاه پرداخت-->>سرویس پرداخت: پرداخت تکمیل شد
    end
    note over سرویس پرداخت: بسته به شیوه پاسخدهی مورد انتظار
    alt
        سرویس پرداخت-->>صاحب تراکنش: هدایت به آدرس صاحب تراکنش
    else
        سرویس پرداخت->>وب‌هوک: فراخوانی وب‌هوک
    end